### ISSUE TITLE
whitenoise.storage.MissingFileError .../ckeditor5-ui/theme/mixins/_rwd.css could not be found when running collectstatic

### ISSUE THREAD

**Issue by jsolly** [hvlads/django-ckeditor-5#69]
#### Context 
I have recently been exploring using [WhiteNoise ](https://whitenoise.evans.io/en/stable/) in my Django app. I see an error whenever I run collectstatic.

#### Steps to Reproduce 
1 - Install WhiteNoise
2 - manage.py collectstatic
Error in terminal

```bash
Post-processing 'django_ckeditor_5/src/custom_plugins/theme/titleform.css' failed!

Traceback (most recent call last):
  File "/Users/johnsolly/Documents/code/blogthedata/django_project/manage.py", line 21, in <module>
    main()
  File "/Users/johnsolly/Documents/code/blogthedata/django_project/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/johnsolly/Documents/code/blogthedata/django_project/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/johnsolly/Documents/code/blogthedata/django_project/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/johnsolly/Documents/code/blogthedata/django_project/venv/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/johnsolly/Documents/code/blogthedata/django_project/venv/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/Users/johnsolly/Documents/code/blogthedata/django_project/venv/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/Users/johnsolly/Documents/code/blogthedata/django_project/venv/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'django_ckeditor_5/src/custom_plugins/theme/@ckeditor/ckeditor5-ui/theme/mixins/_rwd.css' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x106ca5070>.

The CSS file 'django_ckeditor_5/src/custom_plugins/theme/titleform.css' references a file which could not be found:
  django_ckeditor_5/src/custom_plugins/theme/@ckeditor/ckeditor5-ui/theme/mixins/_rwd.css

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

I checked the file and I think there is an issue on line 6 where it attempts to import a CSS file that does not exist.
```css
 @import "@ckeditor/ckeditor5-ui/theme/mixins/_rwd.css";
```

#### Environment
* Version of API: 0.1.3

**Comment by hvlads** [comment]
I think you just need to update django_ckeditor_5 to the latest version. This file is missing in the latest version 'django_ckeditor_5/src/custom_plugins/theme/titleform.css'

**Comment by jsolly** [comment]
I am on 0.1.4 and still getting the same error when running collectstatic with WhiteNoise @hvlads

In order to get WhiteNoise to work with the collectstatic command, I needed to delete ```@import "@ckeditor/ckeditor5-ui/theme/mixins/_rwd.css";``` from django_project/venv/lib/python3.9/site-packages/django_ckeditor_5/static/django_ckeditor_5/src/custom_plugins/theme/titleform.css

This error essentially stops WhiteNoise from working as expected

**Comment by hvlads** [comment]
Yes, you're right! Thanks for the error message. Try version 0.1.5 @jsolly

**Comment by jsolly** [comment]
@hvlads I think this has regressed. I have upgraded my environment to 0.1.7 and I am still seeing the same error. This is preventing my app from building in my CI tool because collectstatic cannot run with whitenoise.

```
The CSS file 'django_ckeditor_5/src/custom_plugins/theme/titleform.css' references a file which could not be found:
  django_ckeditor_5/src/custom_plugins/theme/@ckeditor/ckeditor5-ui/theme/mixins/_rwd.css
```

I get the error on fresh installs of 0.1.7

Can we re-open this issue if you can confirm?

**Comment by hvlads** [comment]
Hi  @jsolly, you're right, try it
`pip install django-ckeditor-5==0.1.8`

**Comment by jsolly** [comment]
I upgraded and it works now. Thanks!
